[package]
name = "rust-lua-audio"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = {version = "0.6", features = ["luajit", "vendored", "module", "macros", "send", "async"]}
